group 'com.rehmanali.flutter_root_jailbreak_checker'
version '1.0-SNAPSHOT'

allprojects {
    repositories {
        google()  // <--- YE ZAROORI HAI
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.rehmanali.flutter_root_jailbreak_checker'
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21 // Play Integrity needs min 19, 21 is safe
    }
}

dependencies {
    implementation 'com.google.android.play:integrity:1.3.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3'
}